### ISSUE TITLE
Could not download commit when a same commit in different repository.

### ISSUE THREAD

**Issue by mazong1123** [Microsoft/GVFS#103]
We setup cache server for our projects hosted on visualstudio.com. We created a repo1 with a lot of commits. After a while, we created a repo2 which has same commits as repo1 - we migrate those commits from repo1 to repo2. Then we deleted repo1 from visualstudio.com. We found that when we gvfs clone repo2 with cache server, the gvfs log said it tries to find commit id from repo1, which caused a "Could not download commit xxx" error.

I found [the source code](https://github.com/Microsoft/GVFS/blob/2797fbb8358bb2e0c12d6f3b42a60b43f7655edf/GVFS/GVFS/CommandLine/GVFSVerb.cs#L369-L388) only use commit id to download certain commit but the commit id may exist in both repo1 and repo2.  I guess that could be the reason why it tries to download the commit from the deleted repo1. 

So the question is: does GVFS support this scenario? Or it should be supported and this is simply a bug?

**Comment by sanoursa** [comment]
If you're referring to the TFS Proxy GVFS cache, then it currently does not understand that two different repos may share the same commit objects.

As for the GVFS client behavior, I think I need more information about the repro steps. You say you cloned repo2 but it tried to download from repo1 - can you provide more specifics from your command line args or log outputs?

**Comment by mazong1123** [comment]
Close this as it's not a client side issue. Thanks @sanoursa for the help.
