### ISSUE TITLE
The GVFS pre-command hook depends on MSVCRT140.dll

### ISSUE THREAD

**Issue by ethomson** [Microsoft/GVFS#108]
The GVFS pre-command hook depends on MSVCRT140.dll.  It would be nice if this were statically linked, instead.  On a base system without the C runtime DLLs installed, GVFS clone fails:

<img width="448" alt="screen shot 2018-06-21 at 12 04 44 pm" src="https://user-images.githubusercontent.com/1130014/41695779-7b7d38f6-754b-11e8-80b1-808b497d5485.png">
<img width="448" alt="screen shot 2018-06-21 at 12 04 52 pm" src="https://user-images.githubusercontent.com/1130014/41695782-7ed0093e-754b-11e8-8735-9aaf735f6b06.png">

    Error: 'C:\Temp\foo' is not a valid GVFS enlistment. Could not get origin url. git error: fatal: pre-command hook aborted command

**Comment by sanoursa** [comment]
Thanks, this is fixed internally and will be pushed up with our next release. What we've actually done is packaged up those dll's and made them available on our myget feed so that we can bundle them up with our installer.

**Comment by sanoursa** [comment]
Fixed in the next release
