### ISSUE TITLE
Unable to Build - Nunit 3.10 not available through nuget feed

### ISSUE THREAD

**Issue by putztzu** [Microsoft/GVFS#115]
Package Restore fails with the following error when attempting to install from NUnit Lite
`Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project GVFS Tests\GVFS.FunctionalTests: Unable to find version '3.10.0-dev-05190' of package 'NUnit'.
  https://api.nuget.org/v3/index.json: Package 'NUnit.3.10.0-dev-05190' is not found on source 'https://api.nuget.org/v3/index.json'.
  https://www.myget.org/F/nunit/api/v3/index.json: Package 'NUnit.3.10.0-dev-05190' is not found on source 'https://www.myget.org/F/nunit/api/v3/index.json'.
. Please see Error List window for detailed warnings and errors.				

Package Restore maintainers say that you need to modify your source, they won't make NUnit 3.10 available.`

**Comment by sanoursa** [comment]
Correct, and see #109. We're working on pushing an update today/tomorrow that fixes this issue. In the meantime, you can just locally change it to 3.10.1 from nuget.org if you want to be unblocked.
