### ISSUE TITLE
BuildGVFSForWindows.bat requires Nuget Package Restore

### ISSUE THREAD

**Issue by putztzu** [Microsoft/GVFS#120]
Reading the newly revised README.md associated with the recent modifications this past week,
I noticed the new way to build outside of Visual Studio.
So,, decided to give it a whirl.

The script throws the Nuget Package Restore needed error several times,
Pastebin is down right now, if you need the full log I can post when Pastebin is back up.
Recommend adding whatever Nuget Package Restore command is appropriate to your script, looking at the documentation I'm unsure whether the MSBuild or the Nuget Package Restore CLI commands are appropriate.

So,
On to next trying to build in Visual Studio !

**Comment by sanoursa** [comment]
Thanks for trying it out! That build script should already be calling the appropriate restore steps - the PreBuild csproj calls another script, RestorePackages.bat, which does both a nuget restore and a dotnet restore.

One thing you may be running into is a known side effect of migrating from .NET Framework to .NET Core/Standard. Visual Studio and msbuild seem to confuse themselves with some cached temp files that they leave around for a project that has been converted, and then report strange errors. The best workaround we've found is to make sure you have committed any changes, then run `git clean -xdf` to get rid of all temp files in the repo. It may be good to also delete the BuildOutput folder (above the repo root). After that, building via the script or from VS should both work.

**Comment by sanoursa** [comment]
Another thing to watch for here is that you may need to update Visual Studio. Let us know if you continue to run into issues here.
