### ISSUE TITLE
Add instructions on how install from PowerShell

### ISSUE THREAD

**Issue by masters3d** [Microsoft/GVFS#124]
I'd like to install this on a VSTS agent silently using powershell. Could you provide instructions on how this can be accomplished or if supported?

>... At the moment, VSTS build doesn’t have a “Get sources” option for GVFS. What we do in the Get sources step is clone a small repo with some scripts init that do our bootstrapping. The next build step is then to actually run `gvfs clone`. I’ll make sure that we investigate a more direct getting-started option for GVFS on the backlog.
https://blogs.msdn.microsoft.com/devops/2017/11/22/devops-and-vsts-videos-from-connect-2017/

**Comment by sanoursa** [comment]
At the moment, you can't use GVFS on hosted VSTS build agents. If you have your own agent on your own hardware, you can certainly install GVFS on there, and then add tasks to your build definitions to make use of GVFS commands.

We don't have an off-the-shelf recipe for silently installing GVFS on a server. It's certainly doable, e.g. we do it for our own GVFS build/test servers. The hardest problem you'll have to solve is authentication - somehow you'll need to generate a personal access token and store it in a way that calls to `git credential` can find it. The details of how you do that are really up to your particular scenario, security requirements, etc.

It appears that you're part of the greater Windows org. If you contact me via email, I can put you in touch with people who have already solved these problems for Windows teams.
