### ISSUE TITLE
How GVFS works

### ISSUE THREAD

**Issue by SamuelEnglard** [Microsoft/GVFS#2]
I'd love there to be an explanation of how CVFS works in detail, not the high level overview that README.md gives. Either in a dedicated file or a README.md for each project.

**Comment by kyrias** [comment]
Would also be useful with a small dictionary explaining some uncommonly used terms, and preferably how they came about, like hydrate.

**Comment by sanoursa** [comment]
I am planning to publish a detailed paper very soon with the history of our design choices and how the current solution works. Coming very soon!

**Comment by moderndev** [comment]
hydrate/dehydrate objects etc I thought was a commonly known thing ...  Was for me, and made complete sense in GVFS's context because you know its all "virtualized" until touched

**Comment by sanoursa** [comment]
Update on this - a single white paper has turned into a project to write a series of articles. The first few of those are written and going through are publishing pipeline. Two of those articles are "GVFS Design History" and "GVFS Internals". So it's taking a little longer than I had initially planned, but it's on its way!

**Comment by sanoursa** [comment]
The first few articles in our Git at Scale article series are now available: https://www.visualstudio.com/learn/git-at-scale/. This first batch includes an article on GVFS design history, and another is coming soon about the current inner workings of GVFS.

**Comment by billziss-gh** [comment]
@sanoursa this is a great write up with genuinely useful information. Thank you for making it public.

**Comment by steveknoblock** [comment]
Thanks for the article. I look forward to learning how you virtualized the access to the filesystem.

**Comment by sanoursa** [comment]
Just published another article with much more information about how GVFS actually works: https://www.visualstudio.com/learn/gvfs-architecture/

**Comment by sanoursa** [comment]
More articles will be coming out over time, but closing this issue out for now since the basics are covered. Please do post questions if you have any!
