### ISSUE TITLE
libgit2 integration?

### ISSUE THREAD

**Issue by rlabrecque** [Microsoft/GVFS#24]
Hey everyone,
I'm just wondering if you're planning on integrating with libgit2 at all?

This is going to be pretty vital for tools.

**Comment by billziss-gh** [comment]
I too would like to see the GVFS protocol integrated into libgit2. If something like this happened, a FUSE solution could become a more realistic possibility.

**Comment by sanoursa** [comment]
The challenge with libgit2 is that it is not caught up to all the features in git that we're using in GVFS. For example, libgit2 doesn't understand the sparse-checkout feature, which is vital to our design.

That said, libgit2 isn't entirely broken. For example, GVFS itself uses libgit2 to read git objects out of packfiles. You just can't do anything with libgit2 that would touch the index or working directory.

**Comment by sanoursa** [comment]
Closing for now but happy to take more questions on the topic.
