### ISSUE TITLE
How does GVFS work in disconnected environment?

### ISSUE THREAD

**Issue by lucasfolino** [Microsoft/GVFS#26]
I thought one of the benefits of git is that you have an entire copy of the repo so you can work disconnected.  Does this cause this git to not have a complete copy?  Does this cause git to be less distributed and more centralized?  I am not against this and see the benefit for large repos.  I am trying to understand what is the trade off.  What  happens if I am disconnected and try to checkout/commit files I do not already have touched?  I guess a more general question is how does GVFS work in a disconnected environment that git was designed for?

**Comment by sanoursa** [comment]
Those are great questions, and you're absolutely right about the tradeoffs. We are adding an online requirement in exchange for the ability to scale.

You can think of GVFS as two main pieces:
- Only download contents when you need them. This adds an online requirement for first-time access to any contents, but you can also bypass it by prefetching the contents you want.
- Make your git commands fast by not letting them scan all 3M+ files in the repo if you're only working with a small subset. This is all purely local logic and doesn't add any requirement to be online.

If you make use of the on-demand downloads (which is the default behavior of GVFS), then yes you need to be online the first time you access a new blob. However, all of your git commands like creating branches, checking status, committing, etc all work offline, as long as you're using contents you already have. And if you know you're going to be offline and want access to a set of files, we also provide a way to prefetch them.
