### ISSUE TITLE
cannot build GVFS, Could someone provide SetupGVFS.exe to me?

### ISSUE THREAD

**Issue by scm20008** [Microsoft/GVFS#29]
I build GVFS failed! Hope someone to share the SetupGVFS.exe to me!

thanks!

**Comment by sanoursa** [comment]
@scm20008 Can you share what build errors you're getting? I may be able to help you get it to build.

**Comment by scm20008** [comment]
@sanoursa 
the build number of win10 is 14393.

In the Chinese environment, the build cannot be sucessful, right?

the following is the build errors:
(tips："错误" means error，“未能找到” and "找不到" means "not found")

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0006	未能找到元数据文件“C:\Repos\GVFS\src\..\BuildOutput\GVFS.GvFltWrapper\bin\x64\Debug\GVFS.GvFltWrapper.dll”	GVFS.GVFlt	C:\Repos\GVFS\src\GVFS\GVFS.GVFlt\CSC	1	活动的
错误	CS0006	未能找到元数据文件“C:\Repos\GVFS\BuildOutput\GVFS.GVFlt\bin\x64\Debug\GVFS.GVFlt.dll”	GVFS.Mount	C:\Repos\GVFS\src\GVFS\GVFS.Mount\CSC	1	活动的
错误	CS0006	未能找到元数据文件“C:\Repos\GVFS\BuildOutput\GVFS.GVFlt\bin\x64\Debug\GVFS.GVFlt.dll”	GVFS	C:\Repos\GVFS\src\GVFS\GVFS\CSC	1	活动的
错误	CS0006	未能找到元数据文件“C:\Repos\GVFS\BuildOutput\GVFS.Mount\bin\x64\Debug\GVFS.Mount.exe”	GVFS	C:\Repos\GVFS\src\GVFS\GVFS\CSC	1	活动的
错误	CS0006	未能找到元数据文件“C:\Repos\GVFS\BuildOutput\GVFS\bin\x64\Debug\GVFS.exe”	GVFS.UnitTests	C:\Repos\GVFS\src\GVFS\GVFS.UnitTests\CSC	1	活动的
错误	CS0006	未能找到元数据文件“C:\Repos\GVFS\BuildOutput\GVFS.GVFlt\bin\x64\Debug\GVFS.GVFlt.dll”	GVFS.UnitTests	C:\Repos\GVFS\src\GVFS\GVFS.UnitTests\CSC	1	活动的

错误		项目 GVFS\GVFS.Common 的 NuGet 程序包还原失败: 找不到“1.9.4”版本的程序包“ManagedEsent”。
  https://api.nuget.org/v3/index.json: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。
  发送请求时出错。未能解析此远程名称: 'api.nuget.org'。
  
错误		项目 GVFS\GVFS 的 NuGet 程序包还原失败: 找不到“1.9.4”版本的程序包“ManagedEsent”。
  https://api.nuget.org/v3/index.json: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。
  发送请求时出错。未能解析此远程名称: 'api.nuget.org'。

错误		项目 GVFS\GVFS.GVFlt 的 NuGet 程序包还原失败: 找不到“1.9.4”版本的程序包“ManagedEsent”。
  https://api.nuget.org/v3/index.json: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。
  发送请求时出错。未能解析此远程名称: 'api.nuget.org'。
  
错误		项目 GVFS Tests\GVFS.FunctionalTests 的 NuGet 程序包还原失败: 找不到“1.9.4”版本的程序包“ManagedEsent”。
  https://api.nuget.org/v3/index.json: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。
  发送请求时出错。未能解析此远程名称: 'api.nuget.org'。
  
错误	C2220	警告被视为错误 - 没有生成“object”文件	GVFS.GvFltWrapper	C:\Repos\GVFS\packages\Microsoft.GVFS.GvFlt.0.17523.1-preview\header\gvlib.h	749

**Comment by sanoursa** [comment]
Looks like you're hitting the same issue as #8. I will try to get that fixed with the next update to GvFlt.

**Comment by scm20008** [comment]
@sanoursa
thanks! my problem has been resolved.
