### ISSUE TITLE
Can you run it against a local TFS?

### ISSUE THREAD

**Issue by florin-crisan** [Microsoft/GVFS#32]
Is there any chance to use GVFS with a local TFS? that would enable us to test it inside the company...

**Comment by sanoursa** [comment]
Not at this time, but it's something we're looking at enabling in a future update of TFS.

**Comment by brunochampoux** [comment]
@sanoursa has the situation changed here? Our company would like to test migrating our large monolithic Perforce depots into Git repos using GVFS against a local TFS. I found mentions that TFS 2018 support GVFS but it seems there is no documentation explaining how to activate it. I have tried to push a JSON configuration with values I found in another issue here but our TFS is still not handling GVFS config queries.
