### ISSUE TITLE
Upgrade option for existing Visual Studio Team Services GIT Repo

### ISSUE THREAD

**Issue by mancoast** [Microsoft/GVFS#33]
This is more of a question:
Does there exist feasibility to upgrade a pre-existing GIT REPO hosted on Visual Studio Team Services?

Thanks!
coast

**Comment by sanoursa** [comment]
All VSTS git repos now support the GVFS protocol. There is no need to upgrade anything.

However, your repo must satisfy some constraints before you can clone it with GVFS: it must not have clean/smudge filters, and it must have a root .gitattributes file.

**Comment by mancoast** [comment]
brilliantly done! Cheers
