### ISSUE TITLE
Rewrite and Expand installation Instructions

### ISSUE THREAD

**Issue by mancoast** [Microsoft/GVFS#35]
Greetings,

The deployment instructions require simplification engineering.
Please elaborate re-write for those of us that "just want to make it go".

Thanks!
coast

**Comment by sanoursa** [comment]
For now, you have to build GVFS yourself and then install it from your build outputs. Once we figure out a release mechanism for GvFlt, we can look at publishing an installer to make it easier.

**Comment by fpqc** [comment]
@sanoursa will the GvFlt driver make it in as an OS component in the Fall Creators update?

**Comment by mancoast** [comment]
A Microsoft signed and distributed driver would allow IT to relax so
Engineering can use these new tools.

**Comment by fpqc** [comment]
@mancoast I think it will be microsoft-signed, just not sure if it will make it in as an optional OS component.

**Comment by sanoursa** [comment]
The latest GvFlt NuGet package now contains a signed driver, so signing is no longer an issue. However I still haven't heard a final answer on how or when there will be an official distribution of it in the OS. I will surely announce that as soon as I know.

**Comment by sanoursa** [comment]
Closing this issue for now. We'll make a bigger announcement whenever we know more about GvFlt distribution.

**Comment by mancoast** [comment]
Thanks!

**Comment by sanoursa** [comment]
Yes you should be able to install it without disabling any driver verification checks. What specific version of GVFS are you trying to install?

**Comment by jkatsman** [comment]
I am using version 0.180125.1-preview, downloaded from here: https://www.nuget.org/packages/Microsoft.GVFS.GvFlt/

I have a folder with GvFlt.inf and GvFlt.sys as contained in the NuGet package. When I then install using 'pnputil -i -a GvFlt.inf' .

`
Microsoft PnP Utility

Processing inf :            GvFlt.inf
Adding the driver package failed : The third-party INF does not contain digital signature information.


Total attempted:              1
Number successfully imported: 0

`

**Comment by sanoursa** [comment]
You should not need to use pnputil to install the driver. Just run the GVFS installer from https://github.com/Microsoft/GVFS/releases.

**Comment by jkatsman** [comment]
Thanks a lot. I was trying to install GvFlt by itself, but from that I think I figured it out.
