### ISSUE TITLE
A kernel mode driver written in C#?

### ISSUE THREAD

**Issue by hgleaves-ncuadmin** [Microsoft/GVFS#39]
Is this a kernel mode filter driver? if so why is most of the source written in C#? Just trying to get some insights.

**Comment by SamuelEnglard** [comment]
The kernel mode driver isn't in the repo and (I'm guessing) is in C/C++

**Comment by sanoursa** [comment]
GvFlt is a kernel mode filter driver that sends some of its requests up to user mode. GVFS is the user mode application that responds to those requests. To greatly oversimplify it, GVFS knows how to enumerate a directory or retrieve file contents, and GvFlt knows how to merge those results into NTFS.
