### ISSUE TITLE
can GVFS support submodule?

### ISSUE THREAD

**Issue by zhuangbiaowei** [Microsoft/GVFS#44]
I got this message:

Submodule operations are not supported on a GVFS repo
fatal: pre-command hook aborted command

**Comment by sanoursa** [comment]
It is not currently supported, as indicated by the error message. I believe it is possible to build support for submodules, but so far we have not had any need for it, so we haven't done that work.

Support for submodules could come in two flavors:
* Enable submodules to work correctly, but everything under the submodule root will be a normal git repo, not virtualized in any way. I suspect this is just a matter of doing some extensive testing but should only require relatively small changes to GVFS.
* Enable submodules to work and be virtualized. This is quite a bit more work. I believe it is possible, but I haven't thought through it in any amount of detail yet.
