### ISSUE TITLE
Virtual Repositories

### ISSUE THREAD

**Issue by Korporal** [Microsoft/GVFS#45]
Something that comes up from time to time is the need to be able to run and debug two versions of an app at the same time, these apps being on different branches in a repo. Git does not really support the concept of having two branches checked out at the same time and so there are other somewhat contrived ways of doing this but they are cumbersome.

However it occurs to me that with GVFS it may be possible to create the abstract idea of a _virtual_ repo.

A virtual repo would be a folder with some form of association to some other (actual repo) folder.

Using GVFS the virtual repo would appear to be a distinct repo and when a branch in the virtual repo gets checked out GVFS would create whatever folders/files are necessary (within the virtual repo's disk folder) by getting them from the "real" repo.

So in a tool (e.g. Smartgit) one might see two repos "main_apps" and "main_apps.2" (the latter being "virtual".

I can then checkout branch_x in one repo and branch_y in the other, but the state of the file system withing the virtual repos (physical) folder is determined by the git history data in the real repo.

Obviously there are issues and questions that arise but assuming these are not showstoppers this could be a very useful feature.

**Comment by Rondom** [comment]
GIT itself already uses hardlinks to de-duplicate objects in .git if you do a local clone (I do not use Windows, but at least under Linux it does). So a clone of a directory on the same filesystem does not take up significantly more space. I agree, that there a several UI-challenges, that make such a workflow bothersome (mainly pushing back changes). I am not sure how well that currently works with Git-VFS under Windows...

As I said, I agree about the user interface-part, but don't think this something that would better be implemented in GIT itself to support the use case you (and many others have) more transparently? What would GIT-VFS solve, what cannot be solved without it? In your use case your files are all there on disk and there is not need to fetch them over the network, what functionality do you expect GIT-VFS to deliver that is not possible without it?

**Comment by sanoursa** [comment]
What you're describing sounds a lot like what [git-worktree](https://git-scm.com/docs/git-worktree) provides. Worktrees allow you to have multiple working directories, and have each one checkout a different branch, without redownloading all the objects.

GVFS doesn't currently support worktrees. However, we are currently working on an object cache that can be shared between multiple clones, and with that feature in place, you can achieve the same goal simply by cloning multiple times.

Would that achieve the end result that you're after?

**Comment by sanoursa** [comment]
Are you referring to the shared cache? Yes that work is completed, and available as of [GVFS 1.0.18026.1](https://github.com/Microsoft/GVFS/releases/tag/v1.0.18026.1) (though there is a more recent release also)
