### ISSUE TITLE
Warning received "Unable to validate your GVFS version"

### ISSUE THREAD

**Issue by mrcaron** [Microsoft/GVFS#47]
I pulled the repo and built GFVS in debug and installed it. I also have TFS 2018 RC2 installed on another machine. I created a git repo on TFS 2018 RC2 server and tried to clone it with gvfs and get the following issue:

![image](https://user-images.githubusercontent.com/72183/31446918-57eb7dfa-ae66-11e7-8610-2db44504d2e5.png)

Is the warning something I should be concerned with ? Was there a step I neglected in building? Does TFS 2018 RC2 not support gvfs fully?

**Comment by sanoursa** [comment]
The warning is benign, so far as your gvfs clone is concerned. What's happening here is that you need to configure the server with some info that it needs to be able to respond to the /gvfs/config query. We are planning to change the server behavior so that it always returns a default response if you haven't configured anything, but that did not make it into RC2. I'll follow up shortly with more details about how to configure it yourself.

**Comment by alepauly** [comment]
@mrcaron: As sanoursa mentioned, we have a change in behavior in the pipeline so the default response will avoid that warning if you haven't configured anything explicitly. In the meantime, you can avoid the warning by configuring an all-encompassing version range on the server. The configuration of allowed GVFS client versions is done through the Git Repository Settings Policy, here are the steps to get that done (you'll need a REST client such as [Postman](https://www.getpostman.com/postman)):
1. Check to make sure you don't have an existing Git Repository Settings Policy by running a `GET `to `https://<host>/tfs/<collection>/<project>/_apis/policy/configurations` and looking for any entries with type Id `"7ed39669-655c-494e-b4a0-a08b4da0fcce"`.
2. If there isn't an existing Git Repository Settings Policy then run a `POST `to `https://<host>/tfs/<collection>/<project>/_apis/policy/configurations?api-version=3.1` with the following body (and `application/json `Content-Type):

```
{
	"isEnabled": true,
	"isBlocking": true,		
	"settings": {
		"scope": [{
			"repositoryId": null
		}],
		"gvfsAllowedVersionRanges": [{
				"min": {
					"major": 0,
					"minor": 0,
					"build": 0,
					"revision": 0
				},
				"max": null
			}
		]
	},
	"type": {
		"id": "7ed39669-655c-494e-b4a0-a08b4da0fcce",
		"displayName": "Git repository settings"
	}
}
```

Note that the Json above sets the scope of the policy to all repos in the project. If you want this to apply to a specific repo then you can get the repo Id by navigating to `https://<host>/tfs/<collection>/<project>/_apis/git/repositories/<reponame>` and substituting `"repositoryId": null` above with `"repositoryId":<Guid>`

3. If there's an existing Git Repository Settings policy that is scoped to your repo (or project that the repo belongs to) then you won't be able to create a new one and instead you need to modify the existing one by running a `PUT` to `https://<host>/tfs/<collection>/<project>/_apis/policy/configurations/<policy number>?api-version=3.1` with the whole body of the existing policy plus the `"gvfsAllowedVersionRanges"` element from the Json above.

Hope this helps, let me know if you have any questions.
