### ISSUE TITLE
ChromeOS

### ISSUE THREAD

**Issue by frankenstein91** [Microsoft/GVFS#53]
Hello Microsoft team,
Thank you for the great idea. I would still like to request an implementation for ChromeOS. I know Chrome is not a product of yours. I would still like to be able to embed GIT under ChromeOS, which is the task of GVFS. It is already possible to mount SMB directories, maybe you can build on it?
Thank you for your help

**Comment by sanoursa** [comment]
This is not something that is on our roadmap right now. Our immediate focus is adding Mac and Linux support.
