### ISSUE TITLE
SSH Protocol Support

### ISSUE THREAD

**Issue by fcharlie** [Microsoft/GVFS#54]
I suggest GVFS Team support SSH protocol。For some people, the SSH protocol is actually easier to access。

We known git fetch and push is call remote server `git-upload-pack` or `git-receive-pack`, Gvfs can also be made into a command, and then either HTTP or SSH server, the user request is converted to the server call this command, get the output of this command. Here are the command arguments I suggested

```
git-gvfs GVFS Implementation
usage: [command] [args] gitdir
    config         show server config
    size           input json object ids, show those size
    pack-objects   pack input oid's objects
    loose-object   --oid; send loose object
    prefetch       --lastPackTimestamp; prefetch transfer
```

When gvfs clone convert to `ssh -X git@example.com git-gvfs pack-objects someone.git`  json data write to stdin, read git-gvfs's stdout as a packfile.

The server is easier to implement, but the client has some trouble

**Comment by sanoursa** [comment]
No plans to expand the protocol support at the moment, though this is something we will likely need to consider again once our implementations on Mac and Linux get farther along.
