### ISSUE TITLE
build and objects download

### ISSUE THREAD

**Issue by shirazLavi** [Microsoft/GVFS#56]
in my case I'm building the whole  project (which also contains dll files), my question is,
does  the blobs objects(that I understand that are the ones increasing the size on disk) will be downloaded 
once they are fetch in the build?

will the move from TFVC to GVFS will still be useful?   or the repository will  grow to a point where working with git will be impossible?

**Comment by sanoursa** [comment]
We have discussed this outside of GitHub, but for completeness here, yes if your build consumes every file, then GVFS will have to download every file. In general, GVFS is best for repos that have many files, but a typical developer only needs to consume a small percentage of them.
