### ISSUE TITLE
Cache server

### ISSUE THREAD

**Issue by stefanes** [Microsoft/GVFS#61]
Cant seem to find much information about GVFS cache servers. What exactly are they and how do you set one up?

I have also observed servers behaving differently when it comes to the `Cache Server: Default` (no `--cache-server-url` on command line).

### VSTS

Everything works just fine (and you get `Using cache server: None` in the output).

### Bitbucket (on-prem)

Cloning this way gives me the following error:
```
Cannot clone @ <path>: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at GVFS.Common.Http.CacheServerResolver.TryResolveUrlFromRemote(String cacheServerName, GVFSConfig gvfsConfig, CacheServerInfo& cacheServer, String& error) in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS.Common\Http\CacheServerResolver.cs:line 59
   at GVFS.CommandLine.GVFSVerb.ResolveCacheServerUrlIfNeeded(ITracer tracer, CacheServerInfo cacheServer, CacheServerResolver cacheServerResolver, GVFSConfig gvfsConfig) in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS\CommandLine\GVFSVerb.cs:line 308
   at GVFS.CommandLine.CloneVerb.Execute() in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS\CommandLine\CloneVerb.cs:line 137
```

Clone works just fine if adding `--cache-server-url None` to the `gvfs clone` command.

**Comment by vtbassmatt** [comment]
Answering half your question: TFS 2018 Update 1 includes an updated TFS proxy which knows how to act as a GVFS cache server. We'll be posting release notes, a blog article, and other documentation soon. The TFS proxy works with both VSTS and TFS.

**Comment by sanoursa** [comment]
Re: the second half of the issue, it appears that Bitbutcket is returning a slightly different response to /gvfs/config than VSTS does, and that's tripping up the cache resolving code. Regardless, GVFS should be more resilient to these differences, and if the service doesn't advertise any cache servers, `Default` and `None` should resolve to the same thing. We'll get this fixed in a future release.

**Comment by stefanes** [comment]
FYI:
@sanoursa Issue [fixed](https://jira.atlassian.com/browse/BSERV-9847?focusedCommentId=1717893&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1717893) on the Bitbucket side of things in **version 0.1.1**.

**Comment by stefanes** [comment]
@vtbassmatt 

> ... TFS proxy which knows how to act as a GVFS cache server ...

Will it be able to act as a GVFS cache server for a repo hosted in e.g. Bitbucket? Or is it tied to only TFS/VSTS?

**Comment by praveentiru** [comment]
Is there any documentation that defines how to replicate cache server behavior independent of TFS?
If no, is there a plan for the same?

**Comment by sanoursa** [comment]
The GVFS protocol is defined here: https://github.com/Microsoft/GVFS/blob/master/Protocol.md. The GVFS client can be configured to point at any URL that implements the required endpoints in that protocol. Beyond that, there's not much specific guidance available on building your own cache server.
