### ISSUE TITLE
How does prefetch work?

### ISSUE THREAD

**Issue by tomspilman** [Microsoft/GVFS#63]
I'm not sure i understand how the prefetch feature works or what it does.

I tried this:

```
gvfs prefetch --files *.sln
```

... and got this result:

```
Authenticating...Succeeded
Querying remote for config...Succeeded
Fetching blobs from https://XXXXX.visualstudio.com/XXXXX/_git/XXXXX...Succeeded

Stats:
  Matched blobs:    4
  Already cached:   3
  Downloaded:       1
```

I suspect here "Downloaded" means we downloaded one file you didn't have cached?

What i find weird is that i can see the VS Solution icon now on one of the `.sln` files... but the other three still show the generic file icon.

Does the prefetch not actually put the file in place?

**Comment by sanoursa** [comment]
By default, prefetch only downloads the git objects into its local cache, but it does not hydrate them into your working directory. If you want it to do that as well, you can pass in the `--hydrate` flag.

**Comment by tomspilman** [comment]
>  you can pass in the `--hydrate` flag.

Ah... that was it.  There is no hint as to what "hydrate" meant so i didn't notice it.

**Comment by sanoursa** [comment]
@tomspilman  you're correct that reading from files does hydrate them. It sounds like there could be a bug with mounting while offline. Please file a new issue for that and we'll take a look. The truth is that we don't have any automated testing around offline scenarios at the moment, so it's entirely possible that bugs have crept in there.

**Comment by tomspilman** [comment]
@sanoursa  - I've submitted the mount issue:  https://github.com/Microsoft/GVFS/issues/80

> you're correct that reading from files does hydrate them. 

From my perspective it would be nice if it did.  We have non-technical users like artists as well as programmers and both assumed that if they opened/used the file it then existed on their machine and could be used when offline.
