### ISSUE TITLE
GVFS using too much memory

### ISSUE THREAD

**Issue by ryanries** [Microsoft/GVFS#65]
GVFS.Mount.exe : 872,556 KB Private Bytes

What does a file system need with almost a gigabyte of memory.

**Comment by sanoursa** [comment]
It's a performance tradeoff. GVFS parses git's index file to know what to project, and uses that information to respond to the gvflt driver's enumeration requests. We have currently optimized completely in favor of being able to answer the enumeration requests as fast as possible, to speed up file system performance, and as a result we have to store the parsed index as a tree structure in memory. If you're working with a repo with a large index file, that ends up consuming a lot of memory. For the Windows repo, this is often in the 1.0-1.2GB range.

That being said, we have some changes currently in progress that reduce this number by about 20%. We're also considering some longer term changes to the driver that would help us reduce it even further. But at the moment, we think holding on to this memory is a good trade for the speed gains we get, especially while running an IO heavy process like a build.

**Comment by ryanries** [comment]
Thanks for the explanation @sanoursa, it makes sense.
