### ISSUE TITLE
gvfs prefetch for a folder and all its content

### ISSUE THREAD

**Issue by acsehi** [Microsoft/GVFS#66]
gvfs prefetch --folders services --verbose --hydrate
Stats:
  Matched blobs:    0
  Already cached:   0
  Downloaded:       0
  Hydrated files:   0

Is there a way to prefetch a folder and all its sub-content? gvfs --folders does not do that and gvfs --files downloads all pattern matching files from the entire repository.

**Comment by sanoursa** [comment]
This is not specified very well (or at all) in the help output for that command, but the expectation is that the folder paths you specify are relative to the root of the directory, not relative to your current working directory (which I'm guessing is why your command is not finding any matched blobs).

If you try running it again with root-relative paths, you should see that it does behave as you expect in terms of recursing into all subfolders as well.

**Comment by acsehi** [comment]
Solved it. Thanks!
