### ISSUE TITLE
Nautilus Trashcan on nfs mounts doesn't work

### ISSUE THREAD

**Issue by pandzieciol** [Microsoft/GVFS#68]
When I delete a file on a nfs share, it's being moved correctly to ".Trash-1000" in the root of the share. I also get correctly an info that it has being deleted, but the trashcan is empty. I can't recover the deleted file any more nor can I empty the trashcan. The trashcan on the server shows the file and allows deletion as well as recovery.

The problem occures on 3.26 and 3.28 (Arch Linux as client, Fedora F27/F28 as server)

**Comment by sanoursa** [comment]
@pandzieciol I think you may have opened this issue on the wrong repo. This doesn't seem related to GVFS.

**Comment by pandzieciol** [comment]
The share is mounted via GVFS.
