### ISSUE TITLE
Rename GVFS to "M$vfs"

### ISSUE THREAD

**Issue by sojirosan** [Microsoft/GVFS#70]
Short for Micro$haft virtual file system.

Gnome has used the name GVfs for YEARS. Why do you greedy jerks think you can just steal this name?

I can only imagine what would happen if I tried to name my own file system NTFS...

**Comment by sojirosan** [comment]
So this is the "extinguish" part in M$'s strategy, right? 

[https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish)

**Comment by extremeheat** [comment]
Congratulations on creating your first Github issue.

When you're using Github issues (or perhaps any issue tracker anywhere), it helps to use the thing called the  *search feature* to make sure that nobody has already created the same issue before. As it turns out (I'll save you the time), your issue mirrors #7, #15, #31 and #36. Also, in general it is good etiquette to not be a dick and not ramble about irrelevant stuff or personal vendettas when you're not adding anything relevant to the conversation.

**Comment by woohooyeah** [comment]
Yeah, it seems they closed these issues, but the problem has clearly not been solved. The repo still has the stolen 'GVFS' acronym, belonging to the GNOME Virtual File System.

A multi-billion dollar corporation, incapable of inventing their own unique names and acronyms? It looks so incredibly dumb. And it's very provocative. Everyone with a functioning set of brains will hold Microsoft in lower esteem because of this.

Sorry to say it, but in my view they do deserve to be flamed for this. Until they correct their behaviour.

**Comment by Licshee** [comment]
TIL each one need a globally unique name

**Comment by sojirosan** [comment]
@extremeheat 
>  Also, in general it is good etiquette to not be a dick and not ramble about irrelevant stuff or personal vendettas when you're not adding anything relevant to the conversation.

And then you do _exactly_ the same thing. Huh... okay. While we're on the subject of hypocrisy, let's not forget about all the projects Microsoft got extremely butthurt over for having the same or similar names as their products:

- [https://wxwidgets.org/about/name-change/](https://wxwidgets.org/about/name-change/)
- [http://www.ghisler.com/name.htm](http://www.ghisler.com/name.htm)
- [https://en.wikipedia.org/wiki/Microsoft_vs._MikeRoweSoft](https://en.wikipedia.org/wiki/Microsoft_vs._MikeRoweSoft)

You know what, I think I'll create my own OS called Windows... Microsoft clearly doesn't care about globally unique names so it should be cool, right? Satya won't mind, will he?

**Comment by woohooyeah** [comment]
> You know what, I think I'll create my own OS called Windows... Microsoft clearly doesn't care about globally unique names so it should be cool, right? Satya won't mind, will he?

Yeah, but you'll have to pretend that the name collision is coincidental too, as in the initial response in #7 .

**Comment by Licshee** [comment]
You surely can do that and try to make people believe you don't know there is a "Microsoft Windows" which take more than half market share on desktop/laptop.

**Comment by mvastola** [comment]
@extremeheat, I'm normally all for the "you catch more flies with honey" approach, but -- as you pointed out -- that was tried in #7, #15, #31 and #36 to no avail. 

Also, while @sojirosan could have commented on the original issue (#7), that would not achieve the same visibility as a new issue which has not yet been closed. This is generally a more direct way of calling Microsoft to task on this issue, especially in light of their acquisition of GitHub -- which, if Microsoft expects to be successful, requires more fully embracing the open source community.

**Comment by sojirosan** [comment]
Thanks @mvastola , that was the entire point of this issue. The name will cause confusion and is also a giant middle finger to the FOSS community. If Microsoft wants to prove that it has changed it's ways, then it needs to respect major conflicts like this. People have argued that it's not a big deal because there are so many examples of similar name conflicts, but none of them are of the same type of project. GVFS and GVfs are both virtual file systems, so there is bound to be significant confusion between the two. In fact, there already has been - people looking for help or info on GVFS may find questions on SO or elsewhere that apply to the other GVFS that will cause confusion. This name is a bad, bad, bad idea, and it will bite M$ in the ass.

**Comment by Licshee** [comment]
I agree microsoft should change the name, but it have nothing to do with openness

> it will bite M$ in the ass

**this** is the reason

**Comment by sam0x17** [comment]
I'm sure people will keep opening name change issues over and over again until this is fixed ;)

**Comment by bet0x** [comment]
I propose PoopVFS, i even made a PR: https://github.com/Microsoft/GVFS/pull/71

**Comment by mvastola** [comment]
@bet0x, you have to sign the Contributor License Agreement for #71 Microsoft will own the copyright to your changes and the right to use your `PoopVFS` name idea. :-)

**Comment by sanoursa** [comment]
I definitely take the name collision seriously. I just opened [an issue](https://github.com/Microsoft/GVFS/issues/72) to brainstorm ideas for a new name for this project
