### ISSUE TITLE
Trying to clone a repo from VSTS

### ISSUE THREAD

**Issue by ravenboilinux** [Microsoft/GVFS#73]
Every  try to clone a repo from VSTS using 'gvfs clone' I get this error:
Error: '' is not a valid GVFS enlistment
[gvfs_clone_20180606_141741.log](https://github.com/Microsoft/GVFS/files/2077619/gvfs_clone_20180606_141741.log)

**Comment by sanoursa** [comment]
I think that release has a bug where you can't clone to a path with spaces in it. Could you try cloning into a path without spaces to see if that resolves it? The next release should already have a fix for this issue.

**Comment by ravenboilinux** [comment]
yeah when i put the %20 in the place for the space in the remote address, it work. Can I change the Folder that it create to not have the %20?

**Comment by sanoursa** [comment]
Yes you can specify what directory to clone into. So for example, you could use something like `gvfs clone https://URL%20With%20Spaces C:\LocalPathWithoutSpaces`

**Comment by ravenboilinux** [comment]
Nice that is great, and helpful. Thank you. We are trying look to get on git with gvfs since reg. git does not work for us.
