### ISSUE TITLE
Broken Link "git at scale" at gvfs.io

### ISSUE THREAD

**Issue by dhcgn** [Microsoft/GVFS#74]
https://gvfs.io/ has a link to https://visualstudio.com/git-at-scale/ which is a Dead End (404).

See: How does it work? > LEARN MORE

**Comment by sanoursa** [comment]
Thank you, yes that link should be https://www.visualstudio.com/learn/git-at-scale/, which now redirects to https://docs.microsoft.com/en-us/azure/devops/git/git-at-scale.

@ethomson mind fixing this up? I've also got a short link that you could consider using instead: https://aka.ms/git-at-scale. That's just for the top level article though. Let me know if you want short links for all of them.

**Comment by ethomson** [comment]
Thanks @dhcgn for reporting this.  Fixed.
